### ISSUE TITLE
[ Request ] Can you update the docs explaining how to train on custom dataset ?

### ISSUE THREAD

**Issue by saurabhvyas** [AlexGidiotis/Document-Classifier-LSTM#1]
I am looking to train on my own dataset, and not Arxiv, I am not sure how to modify code, do you have samples of the final .csv files for train,test and validation ? So maybe, I can convert my dataset into that format.

**Comment by AlexGidiotis** [comment]
@saurabhvyas  I have uploaded sample data and label files. For the data file each text needs to be tokenised with stopwords removed and stored in one line. I also removed punctuation and inserted 'eos' at the end of each sentence for the hierarchical model.

The label file has one line for each text. Be careful not to mess the order since the data generator reads them in the same order.

The validation and test data should have the same format as the training data.
