### ISSUE TITLE
Regarding HAN implementation

### ISSUE THREAD

**Issue by spartian** [AlexGidiotis/Document-Classifier-LSTM#4]
The HAN paper considers only words that appears more than 5 times. I don't think it is implemented in the code. Also, does stop word removal take place in the paper? As I mentioned if stop words are repeated 5 or more times then event they have to be considered. What are your views on this?

**Comment by AlexGidiotis** [comment]
- You are right. Using frequency thresholds some times help but restricting the vocabulary (e.g. to 80k words) usually does the same job.
- Removing stopwords sometimes hurts the performance of lstms but since this is not a language model or summariser I don't thing it is such a big deal.

You are welcome to try both those modifications and let us know if they actually improved the performance.

**Comment by spartian** [comment]
One more question before closing the issue: Has word attention been implemented in HAN ? I asked this because I can see two BILSTM layers in HAN but first a sentence BILSTM is used then word BILSTM is used. Shouldn't it be reverse? or am I missing something?

**Comment by AlexGidiotis** [comment]
That's just me naming the layers in a weird way. The first "sent_blstm" run on a word level and encodes each sentence and then "blstm" runs on a sentence level and encodes the whole document.

**Comment by spartian** [comment]
Thank you for clearing that out......
